language:
  node_js
install:
  - npm install -g codecov
script:
  - jest && codecov


sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 8.11.3
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run validate